# Generated by Django 4.1.5 on 2023-04-29 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('industry', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField(default=None)),
                ('close', models.FloatField(default=None)),
                ('volume', models.IntegerField(default=None)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='us_stocks.company')),
            ],
        ),
    ]
