# Generated by Django 4.1.5 on 2023-04-29 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('us_stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='us_stocks.company', verbose_name='ticker'),
        ),
    ]
